#!/bin/bash

echo "🔐 GitHub Authentication Setup Guide"
echo "====================================="
echo ""
echo "I cannot directly connect to your GitHub account for security reasons,"
echo "but I can guide you through the process to set it up yourself."
echo ""

echo "📋 Choose Your Authentication Method:"
echo ""
echo "1. HTTPS with Personal Access Token (Recommended)"
echo "2. SSH Keys"
echo "3. GitHub CLI (if installed)"
echo ""

read -p "Enter your choice (1-3): " choice

case $choice in
    1)
        echo ""
        echo "🔐 Method 1: HTTPS with Personal Access Token"
        echo "---------------------------------------------"
        echo ""
        echo "Step 1: Create a Personal Access Token"
        echo "1. Go to https://github.com/settings/tokens"
        echo "2. Click 'Generate new token (classic)'"
        echo "3. Give it a name like 'Spring Boot Demo App'"
        echo "4. Set expiration (90 days recommended)"
        echo "5. Select scopes:"
        echo "   - repo (Full control of private repositories)"
        echo "6. Click 'Generate token'"
        echo ""
        echo "Step 2: Configure Git with your credentials"
        echo "git config --global credential.helper store"
        echo ""
        echo "Step 3: When you push to GitHub, enter:"
        echo "Username: YOUR_GITHUB_USERNAME"
        echo "Password: YOUR_PERSONAL_ACCESS_TOKEN"
        echo ""
        echo "💡 Your credentials will be saved for future use!"
        ;;
    2)
        echo ""
        echo "🔑 Method 2: SSH Keys"
        echo "---------------------"
        echo ""
        echo "Step 1: Check for existing SSH keys"
        echo "ls -al ~/.ssh"
        echo ""
        echo "Step 2: Generate new SSH key (if needed)"
        echo "ssh-keygen -t ed25519 -C 'your_email@example.com'"
        echo ""
        echo "Step 3: Add SSH key to ssh-agent"
        echo "eval \"\$(ssh-agent -s)\""
        echo "ssh-add ~/.ssh/id_ed25519"
        echo ""
        echo "Step 4: Add SSH key to GitHub"
        echo "cat ~/.ssh/id_ed25519.pub"
        echo "Copy the output and add it to https://github.com/settings/keys"
        echo ""
        echo "Step 5: Test SSH connection"
        echo "ssh -T git@github.com"
        ;;
    3)
        echo ""
        echo "💻 Method 3: GitHub CLI"
        echo "-----------------------"
        echo ""
        echo "Step 1: Install GitHub CLI (if not installed)"
        echo "# macOS:"
        echo "brew install gh"
        echo ""
        echo "# Windows:"
        echo "winget install --id GitHub.cli"
        echo ""
        echo "Step 2: Authenticate with GitHub"
        echo "gh auth login"
        echo ""
        echo "Follow the prompts to authenticate your account"
        ;;
    *)
        echo "❌ Invalid choice. Please run the script again and choose 1, 2, or 3."
        exit 1
        ;;
esac

echo ""
echo "🎯 After setting up authentication, you can push your code:"
echo ""
echo "# Add remote repository"
echo "git remote add origin https://github.com/YOUR_USERNAME/demo.git"
echo ""
echo "# Push to GitHub"
echo "git push -u origin main"
echo ""
echo "🔗 Helpful Links:"
echo "- GitHub Tokens: https://github.com/settings/tokens"
echo "- SSH Setup: https://docs.github.com/en/authentication/connecting-to-github-with-ssh"
echo "- GitHub CLI: https://cli.github.com/"
echo ""
echo "💡 Need more help? Check the GITHUB_UPLOAD_INSTRUCTIONS.md file in your project!"